CookingSuggestions/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DATA;
namespace CookingSuggestions.Controllers
{
    [Authorize]
    public class CategoryController : Controller
    {
        private readonly IData _repository;

        public CategoryController() : this(new Data()) { }
        public CategoryController(IData data) { _repository = data; }

        public ActionResult Index()
        {
            IList<GetCategoryListResult> model = _repository.getCategories();
            
            return View(model);
        }

        public ActionResult Create()
        {
            DATA.Models.Category model = new DATA.Models.Category();
            model.UserName = User.Identity.Name;
            return View(model);
        }

        //
        // POST: /Category/Create

        [HttpPost]
        public ActionResult Create(DATA.Models.Category model)
        {
            string error = "";
            if (_repository.InsertOrUpdateCategory(null, model.UserName, model.Name, model.DisplayName, model.ImageUrl, model.IsActive, out error))
                return RedirectToAction("Index");
            ModelState.AddModelError("", error);
            return View(model);
        }

        //
        // GET: /Category/Edit/5

        public ActionResult Edit(int id)
        {
            DATA.Models.Category model = (from n in _repository.getCategoryByID(id) select new DATA.Models.Category { 
                ID = n.ID,
                UserName = n.Username,
                Name = n.Name,
                DisplayName = n.DisplayName,
                ImageUrl = n.ImageUrl
            }).SingleOrDefault();
            return View(model);
        }

        //
        // POST: /Category/Edit/5

        [HttpPost]
        public ActionResult Edit(DATA.Models.Category model)
        {
            string error = "";
            if (_repository.InsertOrUpdateCategory(model.ID, model.UserName, model.Name, model.DisplayName, model.ImageUrl, model.IsActive, out error))
                return RedirectToAction("Index");
            ModelState.AddModelError("", error);
            return View(model);
        }
    }
}

CookingSuggestions/Controllers/MenuController.cs
using DATA;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CookingSuggestions.Controllers
{
    [Authorize]
    public class MenuController : Controller
    {
        private readonly IData _repository;
        public MenuController() : this(new Data()) { }
        public MenuController(IData data) { _repository = data; }
        public ActionResult Index()
        {
            IList<GetMenuListResult> model = _repository.getMenuList();
            return View(model);
        }
        public ActionResult Create() {
            DATA.Models.Menu model = new DATA.Models.Menu();
            return View(model);
        }
        [HttpPost]
        public ActionResult Create(DATA.Models.Menu model) {
            string error = "";
            if (_repository.InsertOrUpdateMenu(null, model.Name, model.ImageUrl, model.IsActive, model.Sequence, out error))
                return RedirectToAction("Index");
            ModelState.AddModelError("", error);
            return View(model);
        }
        public ActionResult Edit(int id) {
            DATA.Models.Menu model = (from n in _repository.getMenuByID(id) select new DATA.Models.Menu { 
            ID=n.ID, Name = n.Name, ImageUrl = n.ImageUrl, IsActive = n.IsActive, Sequence = n.Sequence
            }).SingleOrDefault();
            return View(model);
        }
        [HttpPost]
        public ActionResult Edit(DATA.Models.Menu model) {
            string error = "";
            if (_repository.InsertOrUpdateMenu(model.ID, model.Name, model.ImageUrl, model.IsActive, model.Sequence, out error))
                return RedirectToAction("Index");
            ModelState.AddModelError("", error);
            return View(model);
        }
    }
}

CookingSuggestions/Controllers/RecipeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DATA;
namespace CookingSuggestions.Controllers
{
    [Authorize(Roles="SuperAdmin")]
    public class RecipeController : Controller
    {
        private readonly IData _repository;

        public RecipeController() : this(new Data()) { }
        public RecipeController(IData data) {
            _repository = data;
        }
        
        public ActionResult Index(int categoryID)
        {
            IList<GetRecipeForCategoryResult> model = _repository.getRecipesForCategoryID(categoryID);
            ViewBag.categoryID = categoryID;
            return View(model);
        }
        public ActionResult Create(int categoryID) {
            DATA.Models.Recipe model = new DATA.Models.Recipe();

            model.categoryID = categoryID;
            model.Username = User.Identity.Name;

            return View(model);
        }
        [HttpPost]
        public ActionResult Create(DATA.Models.Recipe model) {
            string error = "";
            if (_repository.InsertOrUpdateRecipe(null, model.Username, model.Title, model.Content, model.IsActive, model.ImageUrl, model.HashID, model.Day, model.HolidayTag, out error))
                return RedirectToAction("Index", new { categoryID = model.categoryID });
            ModelState.AddModelError("", error);
            return View(model);
        }
        public ActionResult Edit(int id, int categoryID) {
            DATA.Models.Recipe model = (from n in _repository.getRecipeByID(id)
                                        select new DATA.Models.Recipe
                                        {
                                            ID=n.ID,
                                            Username = n.Username, 
                                            Title = n.Title,
                                            Content = n.Content,
                                            ImageUrl = n.ImageUrl,
                                            IsActive = n.IsActive,
                                            HashID = n.HashID,
                                            CreateDate = n.CreateDate,
                                            UpdateDate = n.UpdateDate,
                                            Day = n.Day,
                                            HolidayTag = n.HolidayTag
                                        }).SingleOrDefault();
            model.categoryID = categoryID;
            return View(model);
        }
        [HttpPost]
        public ActionResult Edit(DATA.Models.Recipe model) {
            string error = "";
            if (_repository.InsertOrUpdateRecipe(model.ID, model.Username, model.Title, model.Content, model.IsActive, model.ImageUrl, model.HashID, model.Day, model.HolidayTag, out error))
                return RedirectToAction("Index", new { categoryID = model.categoryID });
            ModelState.AddModelError("", error);
            return View(model);
        }
    }
}

CookingSuggestions/Controllers/VideoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DATA;
namespace CookingSuggestions.Controllers
{
    [Authorize]
    public class VideoController : Controller
    {
        private readonly IData _repository;

        public VideoController() : this(new Data()) { }
        public VideoController(IData data) { this._repository = data; }

        public ActionResult Index()
        {
            IList<GetVideosListResult> model = _repository.getVideos();
            return View(model);
        }
        public ActionResult Create() {
            DATA.Models.Video model = new DATA.Models.Video();
            model.CreateDate = DateTime.UtcNow;
            model.UpdateDate = DateTime.UtcNow;
            return View(model);
        }
        [HttpPost]
        public ActionResult Create(DATA.Models.Video model) {
            string error = "";
            if (_repository.InsertOrUpdateVideo(null, model.Username, model.Title, model.Description, model.URL, model.IsActive, out error))
                return RedirectToAction("Index");
            ModelState.AddModelError("", error);
            return View(model);
        }
        public ActionResult Edit(int id) {
            DATA.Models.Video model = (from n in _repository.getVideoByID(id) select new DATA.Models.Video { 
                ID = n.ID, Username = n.Username, IsActive = n.IsActive, URL = n.URL, Description = n.Description, Title = n.Title, CreateDate = n.DateCreate, UpdateDate = n.DateUpdated
            }).SingleOrDefault();
            return View(model);
        }
        [HttpPost]
        public ActionResult Edit(DATA.Models.Video model) {
            string error = "";
            if (_repository.InsertOrUpdateVideo(model.ID, model.Username, model.Title, model.Description, model.URL, model.IsActive, out error))
                return RedirectToAction("Index");
            ModelState.AddModelError("", error);
            return View(model);
        }
    }
}

CookingSuggestions/Views/Category/Create.cshtml
@model DATA.Models.Category

@{
    ViewBag.Title = "Create";
}
@section Meni{
    <ul id="menu">
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("Мени", "Index", "Menu")</li>
        <li>@Html.ActionLink("Категории", "Index", "Category")</li>
        <li>@Html.ActionLink("Видеа", "Index", "Video")</li>
    </ul>
}
<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Category</legend>

        @Html.HiddenFor(model=>model.UserName)

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DisplayName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DisplayName)
            @Html.ValidationMessageFor(model => model.DisplayName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.IsActive)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.IsActive)
            @Html.ValidationMessageFor(model => model.IsActive)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ImageUrl)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ImageUrl)
            @Html.ValidationMessageFor(model => model.ImageUrl)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CookingSuggestions/Views/Category/Edit.cshtml
@model DATA.Models.Category

@{
    ViewBag.Title = "Edit";
}
@section Meni{
                           <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("Мени", "Index", "Menu")</li>
                            <li>@Html.ActionLink("Категории", "Index", "Category")</li>
                            <li>@Html.ActionLink("Видеа", "Index", "Video")</li>
                        </ul>
    }
<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Category</legend>

        @Html.HiddenFor(model => model.ID)
        @Html.HiddenFor(model=>model.UserName)


        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DisplayName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DisplayName)
            @Html.ValidationMessageFor(model => model.DisplayName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.IsActive)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.IsActive)
            @Html.ValidationMessageFor(model => model.IsActive)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ImageUrl)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ImageUrl)
            @Html.ValidationMessageFor(model => model.ImageUrl)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CookingSuggestions/Views/Category/Index.cshtml
@model IList<GetCategoryListResult>
@using DATA
@{
    ViewBag.Title = "Index";
}
@section Meni{
                           <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("Мени", "Index", "Menu")</li>
                            <li>@Html.ActionLink("Категории", "Index", "Category")</li>
                            <li>@Html.ActionLink("Видеа", "Index", "Video")</li>
                        </ul>
    }
<h2>Категории</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            Username
        </th>
        <th>
           Name
        </th>
        <th>
            Display Name
        </th>
        <th>
           Is Active
        </th>
        <th>
           Image URL
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Username)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DisplayName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsActive)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ImageUrl)
        </td>
        <td>
            @Html.ActionLink("Recipes", "Index","Recipe", new { categoryID=item.ID },null) |
            @Html.ActionLink("Edit", "Edit", new { id=item.ID })
        </td>
    </tr>
}

</table>